---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      version: "2.26.5"
  install:
    crds: Create
  interval: 5m
  upgrade:
    crds: CreateReplace
  values:
    configuration:
      backupStorageLocation:
        bucket: velero
        config:
          publicUrl: "http://192.168.0.18:9000"
          region: eu-west-3
          s3ForcePathStyle: true
          s3Url: "http://192.168.0.18:9000"
        name: tools
      provider: aws
      resticTimeout: 6h
      volumeSnapshotLocation:
        config:
          region: eu-west-3
        name: aws
    deployRestic: true
    image:
      repository: velero/velero
      tag: v1.8.1
    initContainers:
      - image: "velero/velero-plugin-for-aws:v1.4.0"
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-aws
        volumeMounts:
          - mountPath: /target
            name: plugins
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 25m
        memory: 300Mi
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      resources:
        limits:
          memory: 1000Mi
        requests:
          cpu: 15m
          memory: 200Mi
      tolerations:
        - key: arm
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: 120h
    snapshotsEnabled: true
    upgradeCRDs: false
  valuesFrom:
    - kind: Secret
      name: velero-helm-values
      optional: false
