---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev
spec:
  releaseName: gitea
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitea/gitea
      tag: 1.15.7
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      existingClaim: gitea-pvc
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
        - host: "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "git.${SECRET_DOMAIN}"
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: "tcp"
      http:
        port: 3000
      ssh:
        type: LoadBalancer
        port: 22
        externalTrafficPolicy: Local
        externalIPs:
          - "${SVC_GITEA_ADDRESS}"
    gitea:
      admin:
        email: ${SECRET_EMAIL}
        username: "${SECRET_GITEA_USERNAME}"
        password: ${SECRET_GITEA_ADMIN_PASSWORD}
      security:
        SECRET_KEY: "${SECRET_GITEA_SECRET_KEY}"
      config:
        APP_NAME: "Home Gitea"
        server:
          SSH_PORT: 22
          SSH_LISTEN_PORT: 22
          SSH_DOMAIN: git.${SECRET_DOMAIN}
          root_url: "https://git.${SECRET_DOMAIN}"
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
        mailer:
          enabled: true
          host: "smtp.${SECRET_DOMAIN}:25"
          from: "git@${SECRET_DOMAIN}"
          mailer_type: smtp
      database:
        builtIn:
          postgresql:
            enabled: true
    postgresql:
      persistence:
        existingClaim: gitea-postgresql-pvc
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: dev
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
