---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 5.7.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
  values:
    fullnameOverride: blackbox-exporter
    image:
      repository: quay.io/prometheus/blackbox-exporter
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: &host "blackbox.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    allowIcmp: true
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 2m
        scrapeTimeout: 30s
      targets:
        - name: udmse
          url: 192.168.0.1
          module: icmp
        - name: switch-flex-mini
          url: 192.168.0.56
          module: icmp
        - name: synology-nas
          url: 192.168.0.18
          module: icmp
        - name: qnap-10g
          url: 192.168.0.55
          module: icmp
        - name: haproxy1
          url: 192.168.10.2
          module: icmp
        - name: haproxy2
          url: 192.168.10.3
          module: icmp
        - name: hue-bridge
          url: 192.168.0.46
          module: icmp
    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
        - alert: BlackboxSslCertificateWillExpireSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
          for: 15m
          labels:
            severity: critical
          annotations:
            description: |-
              The SSL certificate for {{"{{ $labels.target }}"}} will expire in less than 3 days
        - alert: BlackboxSslCertificateExpired
          expr: probe_ssl_earliest_cert_expiry - time() <= 0
          for: 15m
          labels:
            severity: critical
          annotations:
            description: |-
              The SSL certificate for {{"{{ $labels.target }}"}} has expired
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 15m
          labels:
            severity: critical
          annotations:
            description: |-
              The host {{"{{ $labels.target }}"}} is currently unreachable
