---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghost
      tag: 5.5.0
    env:
      url: "https://${SECRET_PUBLIC_DOMAIN_2}"
      database__client: mysql
      database__connection__host: ghost-mysql.database
      database__connection__user: ghost
      database__connection__password: ${SECRET_GHOST_MYSQL_PASSWORD}
      database__connection__database: ghost
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production-ovh"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_PUBLIC_DOMAIN_2}"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: "${SECRET_PUBLIC_DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_PUBLIC_DOMAIN_2}"
            secretName: "ghost-tls"
    persistence:
      content:
        enabled: true
        existingClaim: ghost-config
    mariadb:
      enabled: false
