# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: media
type: Opaque
stringData:
    RADARR_APIKEY: ENC[AES256_GCM,data:+GzfyIsbzqXwoiEgAPoG3FHrfzHdCrUJ9lxLLH/Jttk=,iv:Q0qN8BYGM24jsWIcyEu73j305U2CCttv2PfRYIKUDiA=,tag:cPiFiG9qKQtHbo3jFD1ycg==,type:str]
    SONARR_APIKEY: ENC[AES256_GCM,data:lz4eNWtG+eHz/vMndLdTOBVahQOYz4U4Dk/jWA5/5oI=,iv:gcZdmwlGkIm8D20FQdw5BFx0t5u+ypM+4Y0xX7IOuRg=,tag:6F+FCcHrZrvGPdi37HoPlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzNtYThWcUt2Z0lYQk5G
            ZG9tUXJGQkVzMjE2SThyZXRtTGZ5SXpvc1RZCjlRS291bjUxL0RpQ3QvZWEzM3pl
            QlVYMjMrb1lBN1dZVmQ4MDdGaU9EejQKLS0tIDJWNVZXclQzbFBWK1crVmY1bWFN
            eDJydEVNdHdyU0gzaHBLQzk1VlJVNXcK23UUMbMhFII6Ly5Z8Bzy7gFdfFF/O5wk
            aUdPpqH368bNAMYhnsbVmOVYMw7QP3/9jTj5EiJjCbYwclnLImgQig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T01:15:56Z"
    mac: ENC[AES256_GCM,data:hrW26lsc6PIJDMgwGDR/IZCc2sFMV3v/ATSlHuf1IhSo2RnzgaBBPJWm2qsTfKvy1WeIbcxkrMwGc5ujRJuEEWZ89P0YxOhZAmv7kfapKarBWi0SibYPIJ6GpDOvb9DFDo3pa+XWm5ocB5Tng2/WjrZzindDkBax97cO50JP4ss=,iv:Qkd8VPZMnzzBw4hyaQWQWdiUcm4Ios8LN7NMMsxRISo=,tag:XnQNZ9L/R9Qa9gMPkYPzTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
