# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:HNHiDsAPNxsLQHLKPqPPy0RAuK4mmXLs0sLxzuuckZ5u/JNrL8DZxHAgDjB3rq18XC49mmMZOolnMnUafq41FBh1mhcr6AHXE5uBsfoXdRd3K+ySlebjmOQvZLWDB2MdPkuwe00507hkw7TsdkIr6O+WEBtPBlp8,iv:s6DXrQhdQhfwzYRkub5aPCyIz/ekmSMfZItUJucpNUA=,tag:y020JliAge+VMYZKYsrcHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U2tZVW5DaTBBYjFocUJV
            RDZZakoyTWNTcVdPQkVUb2lsK1dxdjM3TFNrCjh6dk9GRFRPdUZtdWhFbk1ESzVE
            YXoxL0M2dkFuelI4aHkvdUtnRVdtMFkKLS0tIE1pSnNmTjFVeTF4S2UySkU3Zmt4
            enFaS3dURjYwTVBOQ1k4Vm9EZWJpWFEKXzNxse7y8TTtt99Ed6OKKOOTRVx0+GYX
            ktRP6EQ0UWtoqDPqjNoyVuKjW8cToT4iUYFewZX/TbvAOtvUyuRIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:44:55Z"
    mac: ENC[AES256_GCM,data:Zr4R8bCoL0Tdp4c++tRk1CjitxgMYKN5h7tJ5QP2UXYtQsJxojk1jfJ5MkSbCLFHCkkjV67cJ8ZFGlCrCEYdfoDCFDGurMcfl3dyjjpN5Y0UqNZxQUnJdrs8+JM7n3Ek5WHpgS0g2zMQ0gmkaBeKxyi/tSFEjsJlMaLZK5aqKWs=,iv:wY31y8jSmGIEyz+tBfQOstkIokVQtLQRG7J9TWJh/Rc=,tag:Zl4ff2ppuG6AUdaTka5PFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
