# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:n/LTW6hUTNWrnSuQx6BxZnZt,iv:6wSZzafNkRzoI1xng4L7duwdtnmPb0CKtXga5nHa67Q=,tag:IokLjR+hzkHNG1pM5hyISA==,type:str]
    api-key: ENC[AES256_GCM,data:q4WtDorjpgY4C3H4xvX5zO038w5B5oVsXX6JXpBoczhcrrOeRw==,iv:Ig58lOAD0/xm5TNxxMt047gZ1oAuDHeKR9tEP3/ps08=,tag:sxtIsbQR17yrmZblzK/sLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WjFhVDhLS2YxUSszMlBt
            dlBLUmZUY0M2R0ZCOEI2dXk5dTRzaDYrVWw0Cm82QWZ3U0NNam5qQXVzVEdLRXJ5
            VUhFbWtXL2VUTjM4MjlXTFgzTndzb3cKLS0tIDhuYjBJVTVlK1pXeWxXVVo2cVVp
            QnY1NUk3UVYvMURubExMdWNYVjF4VjQKlDAo8mRkkBPAoFkWlJgVFnjIFdQ+Jfay
            tTJR3LSmVQHktBYAjbsOBx2bFW7eFuflSjkdKVH1McUg02BrsL8SHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:54:24Z"
    mac: ENC[AES256_GCM,data:r+OmhzpQ9tVDtnnQ1zNXsfi3GKu2Lk0eniUlv4i2WjdI0RXung5uyev5RDGf9ABlvIapown7W6MlUQlD21KAmIs/o1k8zhij0mISCvp61IcTCcjgTxYrGO/QApB7dtBNZ6dv13uul0dCwVNHMsLuK/GqOmr9UyNuDytTl7Y720U=,iv:Iw9OC4Dy1maNlCup1BYV3v3ZAKLmPGdZXCaRJo/D280=,tag:wb8IQcEAAVnlDdiLq/ge7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
