# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:BmgLpU7fahV3D3G1aWu3,iv:PURkahFTkYdczFP9fVJyUH/varxFPGQiEAkV/pscOCE=,tag:VEx4AOIxlxCUScP9c3V7+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMUh1Zjk2RVB4eDVacWRB
            aFRkRXlrajVka0ZsZGdiSkVCM251S2RIc0JJCnlIVjk0U2hMd01mUmwxSTlGNWdn
            ZlF2Sms3dVl3djdpdVZ2ZGRqM2VqL1kKLS0tIFl1dzJxc1VUdXFVdE5wVEx2TUd6
            bWNqOTdnSjRBVFNaUm9VenZUT1RsRDgKkJzjdD82UQiNRrb0cZIB6eAnBNbCPEw8
            ShJHMreJvJRlJyPvRA4wRqPui2JSVe1zo+koMnOwezWDIUjJ0uU8EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:49:16Z"
    mac: ENC[AES256_GCM,data:AtkgRYJsSwVg6jBFlLt7THpneXjDNleEVMVT/rkKWKi5zesLTYI4Fc10tBH1CQfNFt8QnDW6t1+fzBmM9y/BVXO4395r3IouztI4b6bGXR4/zQJouQ1w5FAmQACGyVycyxUjV4Q6avgGSPCyd+5piq/KSYMlOXuuhkLM3ooSvhU=,iv:OMUjv1rfF3wKmEAMUfNxSskVX25qTF48R2mhHqi4tmM=,tag:ivjib4ybrNKs36RH9snrqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
