---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-data
  namespace: database
  labels:
    app.kubernetes.io/name: &name ghost-mysql
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "false"
    snapshot.home.arpa/ignoreAffinity: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
