---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 11.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    # clusterDomain: ${CLUSTER_DOMAIN}
    auth:
      rootPassword: ${SECRET_MARIADB_ROOT_PASSWORD}
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
