---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 4.2.2
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      clientID: ${SECRET_OAUTH2_PROXY_CLIENTID}
      clientSecret: ${SECRET_OAUTH2_PROXY_CLIENTSECRET}
      cookieSecret: ${SECRET_OAUTH2_PROXY_COOKIESECRET}
    extraArgs:
      whitelist-domain: .${SECRET_DOMAIN}
      cookie-domain: .${SECRET_DOMAIN}
      provider: oidc
      oidc-issuer-url: https://${SECRET_DOMAIN}.eu.auth0.com/
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
      path: /oauth2
      hosts: auth.${SECRET_DOMAIN}
      tls:
        - hosts:
            - auth.${SECRET_DOMAIN}
    image:
      tag: latest-arm64
