---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.9.3
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
      interval: 1h
  values:
    expose:
      tls:
        # The ingress controller has a default certificate so we don't need to configure it
        certSource: none
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          core: harbor.${SECRET_DOMAIN}
    externalURL: https://harbor.${SECRET_DOMAIN}
    # logLevel: info
    # expose:
    #   type: ingress
    #   ingress:
    #     hosts:
    #       core: harbor.${SECRET_DOMAIN}
    #       # notary:
    #     annotations:
    #       external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    #       external-dns/is-public: "true"
    #       cert-manager.io/cluster-issuer: letsencrypt-production
    #       kubernetes.io/ingress.class: nginx
    #       ingress.kubernetes.io/ssl-redirect: "true"
    #       ingress.kubernetes.io/proxy-body-size: "0"
    #       nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #       nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #   tls:
    #     certSource: secret
    #     secret:
    #       secretName: harbor-tls
    # externalURL: https://harbor.${SECRET_DOMAIN}
    trivy:
      enabled: true
    chartmuseum:
      enabled: false
    notary:
      enabled: false

    # # Enable When you have found good graphs
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    harborAdminPassword: "${SECRET_HARBOR_ADMIN_PASSWORD}"

    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: registry
        jobservice:
          existingClaim: jobservice
        database:
          existingClaim: database
        redis:
          existingClaim: redis
