---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: *app
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: descheduler-charts
        namespace: flux-system
      interval: 10m
  values:
    kind: Deployment
    replicas: 3
    leaderElection:
      enabled: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: "leases"
      resourceName: "descheduler"
      resourceNamescape: "kube-system"
    # schedule: "*/5 * * * *"
    deschedulerPolicy:
      strategies:
        RemovePodsHavingTooManyRestarts:
          enabled: true
          params:
            podsHavingTooManyRestarts:
              podRestartThreshold: 100
              includingInitContainers: true
        RemovePodsViolatingTopologySpreadConstraint:
          enabled: true
          params:
            includeSoftConstraints: true
        RemoveFailedPods:
          enabled: true
          params:
            failedPods:
              reasons:
                - OutOfcpu
                - CreateContainerConfigError
              includingInitContainers: true
              excludeOwnerKinds:
                - Job
              minPodLifetimeSeconds: 3600
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
    resources:
      requests:
        cpu: 10m
        memory: 30Mi
      limits:
        memory: 50Mi
    service:
      enabled: true
    serviceMonitor:
      enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - *app
              topologyKey: kubernetes.io/hostname
