---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: kube-system
  name: kured
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: kured
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.10.1
  interval: 1h
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.8.2
    updateStrategy: RollingUpdate
    configuration:
      timeZone: "Europe/Paris"
      startTime: "10pm"
      endTime: "2am"
      notifyUrl: "${SECRET_KURED_DISCORD_WEBHOOK}"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    metrics:
      create: true
