---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home-0
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.108.0-b.3
      pullPolicy: Always
    persistence:
      config:
        enabled: true
        existingClaim: adguard-0-config-pvc

    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        port:
          port: 3000

      dns:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: adguard-home-1-dns
          # metallb.universe.tf/loadBalancerIPs: "${SVC_ADGUARD_ADDRESS}"
        loadBalancerIP: ${SVC_ADGUARD_ADDRESS}
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_DOMAIN}"
        hosts:
          - host: "adguard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "adguard.${SECRET_DOMAIN}"
            secretName: tls.adguard

    resources:
      requests:
        memory: 100Mi
        cpu: 20m
      limits:
        memory: 400Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: adguard-home-config

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home-1
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: adguard-home-0
      namespace: networking
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.108.0-b.3
      pullPolicy: Always

    persistence:
      config:
        enabled: true
        existingClaim: adguard-1-config-pvc

    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        port:
          port: 3000

      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_ADGUARD_ADDRESS}
        annotations:
          metallb.universe.tf/allow-shared-ip: adguard-home-0-dns
          # metallb.universe.tf/loadBalancerIPs: "${SVC_ADGUARD_ADDRESS}"
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53

    ingress:
      main:
        enabled: false

    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        memory: 100Mi
        cpu: 20m
      limits:
        memory: 400Mi
