apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-media-manager
  name: plex-media-manager
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
