# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:i2NXyhfFj/SsB5uJeKvBMROeF6YSVzyWHt7v3JjVNIyWThBNeQ==,iv:RxWT36tO+uvNJcz9z9CdHchNpxPPDXzHZV5Pmhzn1EY=,tag:zM9WI8Ej3C9hwUmW/S9HzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZFpJYTBVM01FdVdYVUl2
            S1JXMWNPVkMzR0s0YS80V09VamhtaUtMZkdjCklrekhvY3JZNTlEdCtyRmZUUmNJ
            dXBwbXFDVGQ0STJUS25NWTRkYnBhNHMKLS0tIGo3aDlML3dUYVZBYXBLR0ZscHBp
            OVpiekVGRDA1N3MvanhtMjYxbTNwYVUKm4PUyVvakIRuJ7VgeY6qPYuJ85fKvw2A
            4ldmm3FhZ24sd7OWMeTygnInb/4oI2pACr6gbjQTf4kZuiVLQJ7W7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:49:32Z"
    mac: ENC[AES256_GCM,data:Ip7kCbOSpExAW0SjmSAWEF+AI4ke80CxycYrQHYj+fjTUn5gqC5/bO5leq6Ia5E+A9ZXYl5phud0Uq9yo0vCT+y74ingQ6k10a0hZw2VoOypMtpWJmFaWJcn/sufzA67B2UXKUVBSSbvUM8jDxMQW+p/oE+0mOQmwuyqXVQygEg=,iv:/t4cmhLJTmQq96Vxx/+5EKtOoVBpr9/63SKuxRwtvE4=,tag:fRdY0tj5aloeX/8qrDy3fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
