# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
stringData:
    client-info.yml: ENC[AES256_GCM,data:NCbYAK5S2QRoq/Tn0tLffjfkwIwDI7LGWqGZqoCopSmcND+Pv8Id1Ku6SdjUvV8JAohX6jZS6ypJb8srgrTieOf/Mzip0TEgTboR7eb+exzpFsDOqlEEmxYEW1VJCZd7hg==,iv:HyKyhOPf5MVgzIw93Clf6rlGgCkKqrzFYFnB/w6nwa0=,tag:ZJp8YzW3IPIhy3QCbvQKiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRUZEZ3hzaG54UEM0RG9t
            Z0RSbUJVK3kraXkvWDllclhic1RZZXlZNFVvClNzQjlmUnR4TlJXNkpmYldLNnk4
            TWhVUW9lb3pia1FMWGF1YXpNdGF3VWcKLS0tIDRyTnJSTWtveHVuZlozRm9jUjNE
            RmVQeTFhM3dSalhTc0dPWU1ta2k3RmMK8U9egSWwk84WCInoSb5KcKcocYTPsXjb
            mMosHrnhZL055pme+IRWNx/CLcoXN9R0jaAQrASyVQzVobk6oKMY2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T16:23:24Z"
    mac: ENC[AES256_GCM,data:+2HNgnVgejvnYIUlp8eU+4TlkQz5Qs7N1CZ6CCR9JWbBZ/v2MXrzc53X4AkMDAHXZ8yt78RxUIcdpYkEkfByagYOUMDjlJ3Wcd5Vy8jUNqaA22nOwsFfE6PmRhyOhg9MOwpW84zdbQZgw7BGnOsle3e4SdRxz11QVJpgMmjmxoc=,iv:7Dt4t/6SoWAfQOJPnp4zEJxkLK07L2HzLv3u9H39HJQ=,tag:2llT6MLncQdvwwWiUxKQqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
