---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: littlelink
  namespace: default
spec:
  interval: 5m
  releaseName: littlelink
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: littlelink-server
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/techno-tim/littlelink-server
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      META_TITLE: Moustapha Gueye
      META_DESCRIPTION: Moustapha Gueye Link Page
      META_AUTHOR: Moustapha Gueye
      THEME: Dark
      FAVICON_URL: https://avatars.githubusercontent.com/u/39132800?v=4
      AVATAR_URL: https://avatars.githubusercontent.com/u/39132800?v=4
      AVATAR_2X_URL: https://avatars.githubusercontent.com/u/39132800?v=4
      AVATAR_ALT: Moustapha Gueye
      NAME: Moustapha Gueye
      BIO: Hey! Feel free to reach out to me on any of the below.
      GITHUB: https://github.com/mgueye01
      LINKED_IN: https://linkedin.com/in/moustapha-gueye-39a3a77a
      TWITTER: https://twitter.com/tapha
      EMAIL: mgueye01@gmail.com
      EMAIL_TEXT: Email Me!
      INSTAGRAM: https://www.instagram.com/tapha_g
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "me.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "me.${SECRET_DOMAIN}"
