# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:87CXIYUzX6zKyHFAQqxkDTjcfa4m5pnq4bEMb6E8Ema0BhdhvTEiyFVedIG8CPuu1g6ais/qJ+Mv0wLcFJizQB115gzPAQjssavSvX1gYEh8hEtfqrM7zWUHdeUDdo8tJV8kINLcwRT0R9Rl48fwqUdQSJAbDrKO0YNWzmIG6hUl8b/wMUO6uHGD15Ka8/qqxTHAxsiY+s6bqh02tm2P2+06ApkvImuIXtQy2zUyoDW3fgUmdwYfOK2iVg12tWDdjPEK8HrCVUlnokvvAR0NefKlJ7mTemmZ37BY7XrKLT5sL9Y=,iv:AusXnQtJIPbaqwtPVAheEZDfTyJc9XbU81QVIi1//Dc=,tag:MLCiU3QW/zKhhNNTrWvdug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSnAvMWI5K2QyZENnZFRC
            bWpjbk1WNXhFWHMwYVZnczB6bDZZaW9HekNRCkE0SFhJcUhxUjgrQ0RuNFplcGJ0
            V1JHZXlXTUxGK1lQaUpMcE5wL0JnYTQKLS0tIHo2T2I4a3RlUzlhNCthdlRCSVdY
            dXk2Tjd1bVpOYmE0UWJITWVrVkVNRlEKaJxrztxFx1Xaph73D60AAz3Qzer61h40
            HyxQIF68FkVD8k9hDa2lTxa8mzIniWiI6yJEwVAlCSBiLq6mTLdvyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:50:57Z"
    mac: ENC[AES256_GCM,data:CaB2tJYutyaMssc5O0W4nbKFRKOyWjVdRk5x79+KiKnFPbuZimLMrDxXGGqSryp8bOlnuBNe4xHL22iCMAA+E9sUa0RJ2NUZgWB1wClIcWlqHt9CtGqCCeOwETK/q0rLna0vUgrtwtePthR+2O5lzEoogQr1okU8lJ86emEL3K4=,iv:+pncG1LDPh5dZ649GaDJURueeTCYWEGm9TQNrOBFnPU=,tag:jzIws1cvnY/gi6QIMlFmvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
