---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    toolbox:
      enabled: false
    monitoring:
      enabled: true
    cephClusterSpec:
      dashboard:
        enabled: true
        urlPrefix: /
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: "nginx"
        host:
          name: "rook.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - "rook.${SECRET_DOMAIN}"
      storage:
        useAllNodes: true
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "k8s-3"
            devices:
              - name: "sdb"
              - name: "sda"
          - name: "k8s-2"
            devices:
              - name: "sdb"
              - name: "sda"
          - name: "k8s-1"
            devices:
              - name: "sdb"
              - name: "sda"
          - name: "k8s-0"
            devices:
              - name: "sdb"
              - name: "sda"
    cephFileSystems: []
    cephObjectStores: []
